name: theraphy_physiotherapist_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.0.1'

dependencies: 
  flutter:
    sdk: flutter
  http: ^1.0.0
  image_picker: ^0.8.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logotheraphy.png
