name: theraphy_physiotherapist_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.0.5'

dependencies: 
  flutter:
    sdk: flutter
  http: ^1.0.0
  shared_preferences: ^2.1.2
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logotheraphy.png
    - assets/background.png
