// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8U96UAYxBrB1B_qytLXBAY3kWUhlmtI',
    appId: '1:47089776550:web:0733d75bcbb3f3401ec167',
    messagingSenderId: '47089776550',
    projectId: 'image-host-da1c2',
    authDomain: 'image-host-da1c2.firebaseapp.com',
    storageBucket: 'image-host-da1c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-47xV3Z2vSCr48Z2RHx7AbWdws9Nlb3o',
    appId: '1:47089776550:android:857dbd721fecd5b71ec167',
    messagingSenderId: '47089776550',
    projectId: 'image-host-da1c2',
    storageBucket: 'image-host-da1c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzMrz7686fmWkBPeX74vRXf-I0xkTWb9w',
    appId: '1:47089776550:ios:ed8cb5650b38bb9d1ec167',
    messagingSenderId: '47089776550',
    projectId: 'image-host-da1c2',
    storageBucket: 'image-host-da1c2.appspot.com',
    iosClientId: '47089776550-biu2b22in1t4krcdq6o36higln8dhpee.apps.googleusercontent.com',
    iosBundleId: 'com.example.theraphyPhysiotherapistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzMrz7686fmWkBPeX74vRXf-I0xkTWb9w',
    appId: '1:47089776550:ios:2dabeed087ec69981ec167',
    messagingSenderId: '47089776550',
    projectId: 'image-host-da1c2',
    storageBucket: 'image-host-da1c2.appspot.com',
    iosClientId: '47089776550-54elouqmmauimnhjoctrfs7mo5fef7ie.apps.googleusercontent.com',
    iosBundleId: 'com.example.theraphyPhysiotherapistApp.RunnerTests',
  );
}
